export enum AmmoType {
	normal = 'normal',
	pierce = 'pierce',
	spread = 'spread',
	sticky = 'sticky',
	cluster = 'cluster',
	recover = 'recover',
	poison = 'poison',
	paralysis = 'paralysis',
	sleep = 'sleep',
	exhaust = 'exahust',
	flaming = 'flaming',
	water = 'water',
	freeze = 'freeze',
	thunder = 'thunder',
	dragon = 'dragon',
	slicing = 'slicing',
	wyvern = 'wyvern',
	demon = 'demon',
	armor = 'armor',
	tranq = 'tranq'
}
